#!/usr/bin/env bash

lock() {
    #  killall compton
    betterlockscreen -l blur &
    #  compton -b
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        sudo systemctl suspend
        ;;
    hibernate)
        sudo systemctl hibernate
        ;;
    reboot)
        sudo systemctl reboot
        ;;
    shutdown)
        sudo systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
