#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")
username=$(basename $password)

[[ -n $password ]] || exit

pass_cmd=show
#if pass show "$password" | grep -q '^otpauth://'; then
# test lowercase-password to contain "-otp"
if [[ ${password,,} =~ "-otp" ]]; then
    pass_cmd=otp
fi

if [[ $typeit -eq 0 ]]; then
	wl-copy $username
	sleep 2
	pass $pass_cmd -c "$password" 2>/dev/null
else
	// TODO $username typeit
	pass show 	"$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
	pass $pass_cmd "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
